version: "3"
services:
  db:
    build: ./mysql/
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d #初期処理のフォルダ。初回起動のみでおｋ
      - ./mysql/db:/var/lib/mysql #ここにデータ永続化するためのファイルが入る。
    image: mysqlapp
    container_name: "mysqlapp"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
  rust:
    build:
      context: .
      dockerfile: ./rust/Dockerfile
    links:
      - db
    environment:
      USER: root
    volumes:
      - ./:/rustscraping
    depends_on:
      - db
    ports:
      - 8081:81
    container_name: demo_rust